name: Build and test - CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure_and_make
      run: mkdir build && cd build && cmake .. && make
    - name: test
      run: cd build && ./demo World
